# Generated by Django 5.1 on 2024-09-02 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InLabData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name_object', models.CharField(default='', max_length=7)),
                ('max_score', models.FloatField(default=0)),
                ('min_score', models.FloatField(default=0)),
                ('attempts', models.PositiveIntegerField()),
                ('number_of_question', models.PositiveIntegerField()),
            ],
        ),
    ]
