# Generated by Django 5.1 on 2024-09-05 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InLab',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name_object', models.CharField(max_length=7)),
                ('max_score', models.FloatField(default=0)),
                ('min_score', models.FloatField(default=0)),
                ('attempts', models.PositiveIntegerField()),
                ('number_of_question', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PreLab',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name_object', models.CharField(max_length=7)),
                ('max_score', models.FloatField(default=0)),
                ('min_score', models.FloatField(default=0)),
                ('attempts', models.PositiveIntegerField()),
                ('number_of_question', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='InLabData',
        ),
        migrations.AddField(
            model_name='prelab',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prelabs', to='myApp.user'),
        ),
        migrations.AddField(
            model_name='inlab',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inlabs', to='myApp.user'),
        ),
    ]
