# Generated by Django 5.1 on 2024-09-07 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_remove_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='predict_score',
            field=models.FloatField(default=0),
        ),
    ]
