# Generated by Django 4.2.16 on 2024-09-12 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0004_user_predict_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalData',
            fields=[
                ('studentID', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('prelab1', models.FloatField(default=0)),
                ('inlab1', models.FloatField(default=0)),
                ('prelab2', models.FloatField(default=0)),
                ('inlab2', models.FloatField(default=0)),
                ('prelab3', models.FloatField(default=0)),
                ('inlab3', models.FloatField(default=0)),
                ('prelab4', models.FloatField(default=0)),
                ('inlab4', models.FloatField(default=0)),
            ],
        ),
    ]
