# Generated by Django 4.2.16 on 2024-09-23 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0005_finaldata'),
    ]

    operations = [
        migrations.CreateModel(
            name='predictFinalUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('prelab1', models.FloatField(default=0)),
                ('inlab1', models.FloatField(default=0)),
                ('prelab2', models.FloatField(default=0)),
                ('inlab2', models.FloatField(default=0)),
                ('prelab3', models.FloatField(default=0)),
                ('inlab3', models.FloatField(default=0)),
                ('prelab4', models.FloatField(default=0)),
                ('inlab4', models.FloatField(default=0)),
                ('scorePredict', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mssv', models.CharField(max_length=8)),
                ('question', models.CharField()),
                ('numberOfQuestion', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.AlterField(
            model_name='finaldata',
            name='studentID',
            field=models.CharField(max_length=7, primary_key=True, serialize=False),
        ),
    ]
