# Generated by Django 4.2.16 on 2024-09-23 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0006_predictfinaluser_questiondata_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questiondata',
            name='scorePredict',
            field=models.FloatField(default=0),
        ),
    ]
