# Generated by Django 4.2.16 on 2024-10-08 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0008_googleauthtoken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GoogleAuthToken',
        ),
    ]
